yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  'react-dev-utils@*':
    dependencies:
      typescript: '*'
      webpack: '*'
  '@nestjs/schematics@*':
    dependencies:
      typescript: '*'
