name: shell

on:
  push:
    branches:
      - master
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.7.0
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2.3.4
      - name: Check shell scripts
        run: ' find . -type f \( -name "*.sh" \) -print | while IFS="" read -r file; do shellcheck "$file"; done; '
